# Numpy

## Creating Numpy Arrays

In [216]:
# np.array
import numpy as np


a = np.array([1,3,4])
print(a)

[1 3 4]


In [217]:
type(a)

numpy.ndarray

In [218]:
# 2D and 3D array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [219]:
c = np.array([[[2,3],[3,4],[5,6],[7,8]]])

print(c)


[[[2 3]
  [3 4]
  [5 6]
  [7 8]]]


In [220]:
# dtype
np.array([2,3,4], dtype=float)


array([2., 3., 4.])

In [221]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [222]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [223]:
# with reshape
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [224]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [225]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [226]:
np.random.random((3,4))

array([[0.55218837, 0.54983508, 0.05822678, 0.97145073],
       [0.39890909, 0.70242627, 0.28272269, 0.58039718],
       [0.13915464, 0.12741896, 0.01878369, 0.55865685]])

In [227]:
# np.linspace
np.linspace(-10,10,)


array([-10.        ,  -9.59183673,  -9.18367347,  -8.7755102 ,
        -8.36734694,  -7.95918367,  -7.55102041,  -7.14285714,
        -6.73469388,  -6.32653061,  -5.91836735,  -5.51020408,
        -5.10204082,  -4.69387755,  -4.28571429,  -3.87755102,
        -3.46938776,  -3.06122449,  -2.65306122,  -2.24489796,
        -1.83673469,  -1.42857143,  -1.02040816,  -0.6122449 ,
        -0.20408163,   0.20408163,   0.6122449 ,   1.02040816,
         1.42857143,   1.83673469,   2.24489796,   2.65306122,
         3.06122449,   3.46938776,   3.87755102,   4.28571429,
         4.69387755,   5.10204082,   5.51020408,   5.91836735,
         6.32653061,   6.73469388,   7.14285714,   7.55102041,
         7.95918367,   8.36734694,   8.7755102 ,   9.18367347,
         9.59183673,  10.        ])

In [228]:
np.linspace(-10,10,10, dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [229]:
np.identity(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [230]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [231]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [232]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [233]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [234]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [235]:
a1.ndim # checks dimensions

1

In [236]:
a2.ndim

2

In [237]:
a3.ndim

3

In [238]:
a2.shape

(3, 4)

In [239]:
# shape - No of items in ever dimensions
print(a3)
a3

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [240]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [241]:
# item size - how much size occupy in memory
a3.itemsize


8

In [242]:
# dtype - data type
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


## Changing Datatype

In [243]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## Array Operations

In [244]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [245]:
# Scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [246]:
# relational
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [247]:
# vector operations
# arithmetic */+-
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

## Array Functions

In [257]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[58., 69., 75.],
       [82., 76., 73.],
       [76., 46., 41.]])

In [258]:
# max/min/sum/prod
# 0 -> col & 1 -> row
np.min(a1,axis=0)

array([58., 46., 41.])

In [259]:
# mean/median/std/var
np.mean(a1)

np.float64(66.22222222222223)

In [260]:
np.median(a1, axis=0)

array([76., 69., 73.])

In [262]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [263]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [264]:
# log and exponents
np.exp(a1)

array([[1.54553894e+25, 9.25378173e+29, 3.73324200e+32],
       [4.09399696e+35, 1.01480039e+33, 5.05239363e+31],
       [1.01480039e+33, 9.49611942e+19, 6.39843494e+17]])

In [265]:
# round/floor/ceil
np.round(np.random.random((2,3))*100)


array([[88., 49., 76.],
       [61., 29., 70.]])

## Indexing and Slicing

In [275]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [276]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [277]:
a1[-1]

np.int64(9)

In [278]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [279]:
a2[1,2]

np.int64(6)

In [280]:
a2[1,0]

np.int64(4)

In [281]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [282]:
a3[1,0,1]

np.int64(5)

In [283]:
a3[0,1,0]

np.int64(2)

In [284]:
a3[0,0,0]

np.int64(0)

In [285]:
a3[1,1,0]

np.int64(6)

In [286]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [287]:
a1[2:5]

array([2, 3, 4])

In [288]:
a1[2:5:2]

array([2, 4])

In [289]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [290]:
a2[0,:] # rows and columns

array([0, 1, 2, 3])

In [291]:
a2[:,2]

array([ 2,  6, 10])

In [292]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [293]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [294]:
a2[::2,1:3]

array([[ 1,  2],
       [ 9, 10]])

In [295]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [296]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [297]:
a2[1,::3]

array([4, 7])

In [298]:
a2[0:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [299]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [300]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [301]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [302]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [303]:
a3[0,1,:]

array([3, 4, 5])

In [304]:
a3[1,:,1]

array([10, 13, 16])

In [305]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [306]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## Iterating

In [307]:
for i in a1:
    print(i)


0
1
2
3
4
5
6
7
8
9


In [308]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [309]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [310]:
for i in np.nditer(a3): # used to print nD array one by one
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping

In [311]:
# Reshape

In [312]:
# Transpose
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [313]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [314]:
a2.T # short form to do transpose

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [315]:
# ravel - converts nD to 2D array
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking

In [316]:
# horizontal Stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [317]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [318]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

In [319]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [320]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [321]:
# Vertical splitting
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]