# Numpy

## Creating Numpy Arrays

In [2]:
# np.array
import numpy as np

a = np.array([1,3,4])
print(a)

[1 3 4]


In [3]:
type(a)

numpy.ndarray

In [5]:
# 2D and 3D array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[[2,3],[3,4],[5,6],[7,8]]])

print(c)


[[[2 3]
  [3 4]
  [5 6]
  [7 8]]]


In [ ]:
# dtype
np.array([2,3,4], dtype=float)


array([2., 3., 4.])

In [7]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [9]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# with reshape
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.random.random((3,4))

array([[0.8689207 , 0.17868303, 0.93271517, 0.97655119],
       [0.73785293, 0.16708377, 0.02546512, 0.08854277],
       [0.63993126, 0.50245383, 0.46593529, 0.33299616]])

In [ ]:
# np.linspace
np.linspace(-10,10,)


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [31]:
np.linspace(-10,10,10, dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [27]:
np.identity(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [34]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [41]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [39]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [207]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1.ndim # checks dimensions

1

In [43]:
a2.ndim

2

In [44]:
a3.ndim

3

In [50]:
a2.shape

(3, 4)

In [ ]:
# shape - No of items in ever dimensions
print(a3)
a3

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [52]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [55]:
# item size - how much size occupy in memory
a3.itemsize


8

In [ ]:
# dtype - data type
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


## Changing Datatype

In [60]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## Array Operations

In [69]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [72]:
# Scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [73]:
# relational
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
# vector operations
# arithmetic */+-
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

## Array Functions

In [99]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[22., 42., 93.],
       [49., 33., 17.],
       [72., 40., 19.]])

In [110]:
# max/min/sum/prod
# 0 -> col & 1 -> row
np.min(a1,axis=0)

array([22., 33., 17.])

In [111]:
# mean/median/std/var
np.mean(a1)

np.float64(43.0)

In [113]:
np.median(a1, axis=0)

array([49., 40., 19.])

In [115]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [117]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [118]:
# log and exponents
np.exp(a1)

array([[3.58491285e+09, 1.73927494e+18, 2.45124554e+40],
       [1.90734657e+21, 2.14643580e+14, 2.41549528e+07],
       [1.85867175e+31, 2.35385267e+17, 1.78482301e+08]])

In [ ]:
# round/floor/ceil
np.round(np.random.random((2,3))*100)


array([[70.,  5., 80.],
       [ 5., 40., 48.]])

## Indexing and Slicing

In [127]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [128]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
a1[-1]

np.int64(9)

In [130]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
a2[1,2]

np.int64(6)

In [132]:
a2[1,0]

np.int64(4)

In [133]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [134]:
a3[1,0,1]

np.int64(5)

In [135]:
a3[0,1,0]

np.int64(2)

In [136]:
a3[0,0,0]

np.int64(0)

In [137]:
a3[1,1,0]

np.int64(6)

In [138]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
a1[2:5]

array([2, 3, 4])

In [140]:
a1[2:5:2]

array([2, 4])

In [141]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [142]:
a2[0,:]

array([0, 1, 2, 3])

In [143]:
a2[:,2]

array([ 2,  6, 10])

In [145]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [146]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [148]:
a2[::2,1:3]

array([[ 1,  2],
       [ 9, 10]])

In [149]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [152]:
a2[1,::3]

array([4, 7])

In [154]:
a2[0:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [155]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [156]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [157]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [158]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [159]:
a3[0,1,:]

array([3, 4, 5])

In [160]:
a3[1,:,1]

array([10, 13, 16])

In [162]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [173]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## Iterating

In [179]:
for i in a1:
    print(i)


0
1
2
3
4
5
6
7
8
9


In [180]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [181]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [183]:
for i in np.nditer(a3): # used to print nD array one by one
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping

In [184]:
# Reshape

In [185]:
# Transpose
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [186]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [188]:
a2.T # short form to do transpose

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [189]:
# ravel - converts nD to 2D array
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking

In [196]:
# horizontal Stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [198]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [200]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

In [201]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [204]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [206]:
# Vertical splitting
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]