## `np.sort`
Returns a sorted copy of the array.

```python
np.sort([3,1,2])  # [1 2 3]

In [2]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([81, 98, 47, 95, 30, 94, 65, 49, 39, 68, 43, 71, 92, 59, 95],
      dtype=int32)

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[91, 47, 63, 90],
       [15, 40, 57, 70],
       [74, 33,  3, 51],
       [ 9, 14, 34, 77],
       [86, 35, 64, 21],
       [76, 65, 46, 63]], dtype=int32)

In [4]:
np.sort(a)

array([30, 39, 43, 47, 49, 59, 65, 68, 71, 81, 92, 94, 95, 95, 98],
      dtype=int32)

In [5]:
np.sort(a)[::-1]

array([98, 95, 95, 94, 92, 81, 71, 68, 65, 59, 49, 47, 43, 39, 30],
      dtype=int32)

In [6]:
np.sort(b) #row wise sorting in 2D

array([[47, 63, 90, 91],
       [15, 40, 57, 70],
       [ 3, 33, 51, 74],
       [ 9, 14, 34, 77],
       [21, 35, 64, 86],
       [46, 63, 65, 76]], dtype=int32)

In [7]:
np.sort(b, axis=0) # col wise sorting

array([[ 9, 14,  3, 21],
       [15, 33, 34, 51],
       [74, 35, 46, 63],
       [76, 40, 57, 70],
       [86, 47, 63, 77],
       [91, 65, 64, 90]], dtype=int32)

## `np.append`
Appends values to the end of an array.

```python
np.append([1,2],[3,4])  # [1 2 3 4]


In [10]:
np.append(a,200)

array([ 81,  98,  47,  95,  30,  94,  65,  49,  39,  68,  43,  71,  92,
        59,  95, 200])

In [11]:
b

array([[91, 47, 63, 90],
       [15, 40, 57, 70],
       [74, 33,  3, 51],
       [ 9, 14, 34, 77],
       [86, 35, 64, 21],
       [76, 65, 46, 63]], dtype=int32)

In [14]:
np.append(b, np.ones((b.shape[0],1)),axis=1)

array([[91., 47., 63., 90.,  1.],
       [15., 40., 57., 70.,  1.],
       [74., 33.,  3., 51.,  1.],
       [ 9., 14., 34., 77.,  1.],
       [86., 35., 64., 21.,  1.],
       [76., 65., 46., 63.,  1.]])

In [15]:
np.append(b, np.random.random((b.shape[0],1)),axis=1)

array([[9.10000000e+01, 4.70000000e+01, 6.30000000e+01, 9.00000000e+01,
        6.39133909e-02],
       [1.50000000e+01, 4.00000000e+01, 5.70000000e+01, 7.00000000e+01,
        7.65989401e-02],
       [7.40000000e+01, 3.30000000e+01, 3.00000000e+00, 5.10000000e+01,
        2.32795905e-01],
       [9.00000000e+00, 1.40000000e+01, 3.40000000e+01, 7.70000000e+01,
        4.70194933e-01],
       [8.60000000e+01, 3.50000000e+01, 6.40000000e+01, 2.10000000e+01,
        7.26996044e-01],
       [7.60000000e+01, 6.50000000e+01, 4.60000000e+01, 6.30000000e+01,
        3.30645594e-01]])

## `np.concatenate`
Joins arrays along an axis.

```python
np.concatenate([[1,2],[3,4]], axis=0)

In [16]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## `np.unique`
Returns unique elements.

```python
np.unique([1,1,2,3])  # [1 2 3]

In [22]:
e = np.array([1,1,1,1,2,3,4,5,6,4,4,78,78,78])

In [23]:
np.unique(e)

array([ 1,  2,  3,  4,  5,  6, 78])

## `np.expand_dims`
Adds a new axis.

```python
np.expand_dims([1,2,3], axis=0)


In [24]:
a

array([81, 98, 47, 95, 30, 94, 65, 49, 39, 68, 43, 71, 92, 59, 95],
      dtype=int32)

In [26]:
a.shape

(15,)

In [ ]:
np.expand_dims(a, axis=0) #.shape  #2D

(1, 15)

In [ ]:
np.expand_dims(a,axis=0).shape #row

(1, 15)

In [30]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [ ]:
np.expand_dims(a,axis=1) #col

array([[81],
       [98],
       [47],
       [95],
       [30],
       [94],
       [65],
       [49],
       [39],
       [68],
       [43],
       [71],
       [92],
       [59],
       [95]], dtype=int32)

## `np.where`
Returns indices where condition is true.

```python
np.where([1,0,1])  # (array([0,2]),)


In [33]:
a

array([81, 98, 47, 95, 30, 94, 65, 49, 39, 68, 43, 71, 92, 59, 95],
      dtype=int32)

In [35]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  3,  5,  6,  9, 11, 12, 13, 14]),)

In [36]:
# replace all values > 50 with 0
# np.where(condition,true,false)
np.where(a>50,0,a)

array([ 0,  0, 47,  0, 30,  0,  0, 49, 39,  0, 43,  0,  0,  0,  0],
      dtype=int32)

In [39]:
# replace even values with 0
np.where(a%2==0,0,a)

array([81,  0, 47, 95,  0,  0, 65, 49, 39,  0, 43, 71,  0, 59, 95],
      dtype=int32)

## `np.argmax`
Returns index of maximum value.

```python
np.argmax([1,5,2])  # 1


In [40]:
a

array([81, 98, 47, 95, 30, 94, 65, 49, 39, 68, 43, 71, 92, 59, 95],
      dtype=int32)

In [41]:
np.argmax(a)

np.int64(1)

In [42]:
b

array([[91, 47, 63, 90],
       [15, 40, 57, 70],
       [74, 33,  3, 51],
       [ 9, 14, 34, 77],
       [86, 35, 64, 21],
       [76, 65, 46, 63]], dtype=int32)

In [ ]:
np.argmax(b,axis=1)

array([0, 3, 0, 3, 0, 0])

In [48]:
a

array([81, 98, 47, 95, 30, 94, 65, 49, 39, 68, 43, 71, 92, 59, 95],
      dtype=int32)

In [47]:
# np.argmin
np.argmin(a)

np.int64(4)

## `np.cumsum`
Cumulative sum of elements.

```python
np.cumsum([1,2,3])  # [1 3 6]


In [49]:
a

array([81, 98, 47, 95, 30, 94, 65, 49, 39, 68, 43, 71, 92, 59, 95],
      dtype=int32)

In [50]:
np.cumsum(a)

array([  81,  179,  226,  321,  351,  445,  510,  559,  598,  666,  709,
        780,  872,  931, 1026])

In [51]:
b

array([[91, 47, 63, 90],
       [15, 40, 57, 70],
       [74, 33,  3, 51],
       [ 9, 14, 34, 77],
       [86, 35, 64, 21],
       [76, 65, 46, 63]], dtype=int32)

In [52]:
np.cumsum(b)

array([  91,  138,  201,  291,  306,  346,  403,  473,  547,  580,  583,
        634,  643,  657,  691,  768,  854,  889,  953,  974, 1050, 1115,
       1161, 1224])

In [53]:
np.cumsum(b,axis=0)

array([[ 91,  47,  63,  90],
       [106,  87, 120, 160],
       [180, 120, 123, 211],
       [189, 134, 157, 288],
       [275, 169, 221, 309],
       [351, 234, 267, 372]])

In [54]:
np.cumsum(b,axis=1)

array([[ 91, 138, 201, 291],
       [ 15,  55, 112, 182],
       [ 74, 107, 110, 161],
       [  9,  23,  57, 134],
       [ 86, 121, 185, 206],
       [ 76, 141, 187, 250]])

In [56]:
# np.cumprod -> cumulative product
np.cumprod(a)

array([                  81,                 7938,               373086,
                   35443170,           1063295100,          99949739400,
              6496733061000,      318339919989000,    12415256879571000,
         844237467810828000,  -591277031553499232, -5087181092879342240,
       -6852058702160695680,  1556906194129090432,   332135852587178112])

In [57]:
a

array([81, 98, 47, 95, 30, 94, 65, 49, 39, 68, 43, 71, 92, 59, 95],
      dtype=int32)

## `np.percentile`
Computes percentile value.

```python
np.percentile([1,2,3,4], 50)  # 2.5


In [59]:
np.percentile(a,100)

np.float64(98.0)

In [60]:
np.percentile(a,0)

np.float64(30.0)

In [61]:
np.percentile(a,50)

np.float64(68.0)

In [62]:
np.median(a)

np.float64(68.0)

## `np.histogram`
Computes histogram of data.

```python
np.histogram([1,1,2,3], bins=2)


In [63]:
a

array([81, 98, 47, 95, 30, 94, 65, 49, 39, 68, 43, 71, 92, 59, 95],
      dtype=int32)

In [65]:
np.histogram(a,bins=[0,50,100]) # frequency count

(array([ 5, 10]), array([  0,  50, 100]))

## `np.corrcoef`
Returns correlation matrix.

```python
np.corrcoef([1,2,3],[1,5,7])


In [84]:
salary = np.array([20000, 40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

## `np.isin`
Membership test.

```python
np.isin([1,2,3],[2])  # [False True False]


In [86]:
a

array([81, 98, 47, 95, 30, 94, 65, 49, 39, 68, 43, 71, 92, 59, 95],
      dtype=int32)

In [88]:
items = [10,20,30,40,50,60,70,80,90]
np.isin(a,items)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False])

In [89]:
a[np.isin(a, items)]

array([30], dtype=int32)

## `np.flip`
Reverses array.

```python
np.flip([1,2,3])  # [3 2 1]


In [97]:
b

array([[91, 47, 63, 90],
       [15, 40, 57, 70],
       [74, 33,  3, 51],
       [ 9, 14, 34, 77],
       [86, 35, 64, 21],
       [76, 65, 46, 63]], dtype=int32)

In [ ]:
np.flip(b) # row

array([[63, 46, 65, 76],
       [21, 64, 35, 86],
       [77, 34, 14,  9],
       [51,  3, 33, 74],
       [70, 57, 40, 15],
       [90, 63, 47, 91]], dtype=int32)

In [ ]:
np.flip(b, axis=0) # col wise

array([[76, 65, 46, 63],
       [86, 35, 64, 21],
       [ 9, 14, 34, 77],
       [74, 33,  3, 51],
       [15, 40, 57, 70],
       [91, 47, 63, 90]], dtype=int32)

## `np.put`
Replaces elements at given indices.

```python
a = np.array([1,2,3])
np.put(a, [0,2], [9,9])


In [103]:
a

array([81, 98, 47, 95, 30, 94, 65, 49, 39, 68, 43, 71, 92, 59, 95],
      dtype=int32)

In [104]:
np.put(a,[0,1],[110,530])

In [105]:
a

array([110, 530,  47,  95,  30,  94,  65,  49,  39,  68,  43,  71,  92,
        59,  95], dtype=int32)

## `np.delete`

Deletes elements along a specified axis.

```python
np.delete(arr, index, axis=None)


In [107]:
a

array([110, 530,  47,  95,  30,  94,  65,  49,  39,  68,  43,  71,  92,
        59,  95], dtype=int32)

In [109]:
np.delete(a,[0,2,4]) # arr,[indices]

array([530,  95,  94,  65,  49,  39,  68,  43,  71,  92,  59,  95],
      dtype=int32)

# Set Functions

NumPy provides set operations for 1D arrays that treat arrays as mathematical sets.

---

## `np.union1d(a, b)`

Returns the sorted union of two arrays.

```python
np.union1d([1, 2, 3], [3, 4, 5])  # [1 2 3 4 5]

In [112]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(n,m)

array([1, 2, 3, 4, 5, 6, 7])

## `np.intersect1d(a, b)`

Returns the sorted intersection (common elements) of two arrays.
```python
np.intersect1d([1, 2, 3], [2, 3, 4])  # [2 3]



In [113]:
np.intersect1d(m,n)

array([3, 4, 5])

## `np.setdiff1d(a, b)`

Returns elements in a that are not in b.
```python
np.setdiff1d([1, 2, 3], [2, 3])  # [1]

In [114]:
np.setdiff1d(n,m)

array([6, 7])

##  `np.setxor1d(a, b)`

Returns elements that are in either a or b but not in both.
```python
np.setxor1d([1, 2, 3], [2, 3, 4])  # [1 4]


In [115]:
np.setxor1d(n,m)

array([1, 2, 6, 7])

## `np.clip`

Clips values in an array to a specified range.

```python
np.clip(arr, min_val, max_val)

In [125]:
a

array([110, 530,  47,  95,  30,  94,  65,  49,  39,  68,  43,  71,  92,
        59,  95], dtype=int32)

In [127]:
np.clip(a,a_min=40, a_max=75)

array([75, 75, 47, 75, 40, 75, 65, 49, 40, 68, 43, 71, 75, 59, 75],
      dtype=int32)